services:
  postgres:
    image: postgres:18
    container_name: pdns-postgres
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./postgres:/var/lib/postgresql
      
  pdns:
    build: .
    container_name: pdns
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:8081:8081"

    volumes:
      - ./pdns.conf.template:/etc/powerdns/pdns.conf.template:ro
      - ./pdns-data:/var/lib/powerdns

  dnscontrol:
    image: ghcr.io/stackexchange/dnscontrol:latest
    container_name: dnscontrol
    working_dir: /dns
    env_file:
      - .env
    volumes:
      - ./dnscontrol:/dns
      




